servers:
- {url: 'http://localhost:8080/api/'}
openapi: 3.0.0
paths:
  /vuelo/arrive/{key}:
    put:
      summary: /vuelo arrive
      operationId: /vuelo_arrive
      responses:
        '200': {description: Response 200}
      parameters:
      - schema: {type: string}
        in: path
        name: key
        required: true
      tags: [/vuelo]
  /aeronave/:
    get:
      summary: /aeronave getAll
      operationId: /aeronave_getAll
      responses:
        '200': {description: Response 200}
      tags: [/aeronave]
  /vuelo/{key}:
    get:
      summary: /vuelo getByKey
      operationId: /vuelo_getByKey
      responses:
        '200': {description: Response 200}
      parameters:
      - schema: {type: string}
        in: path
        name: key
        required: true
      tags: [/vuelo]
    delete:
      summary: /vuelo delete
      operationId: /vuelo_delete
      responses:
        '200': {description: Response 200}
      parameters:
      - schema: {type: string}
        in: path
        name: key
        required: true
      tags: [/vuelo]
    put:
      summary: /vuelo edit
      requestBody:
        content:
          application/json:
            schema: {type: object}
      operationId: /vuelo_edit
      responses:
        '200': {description: Response 200}
      parameters:
      - schema: {type: string}
        in: path
        name: key
        required: true
      tags: [/vuelo]
  /vuelo/registro:
    post:
      summary: /vuelo register
      requestBody:
        content:
          application/json:
            schema: {type: object}
      operationId: /vuelo_register
      responses:
        '200': {description: Response 200}
      tags: [/vuelo]
  /vuelo/:
    get:
      summary: /vuelo getAll
      operationId: /vuelo_getAll
      responses:
        '200': {description: Response 200}
      tags: [/vuelo]
  /vuelo/cancel/{key}:
    put:
      summary: /vuelo cancel
      operationId: /vuelo_cancel
      responses:
        '200': {description: Response 200}
      parameters:
      - schema: {type: string}
        in: path
        name: key
        required: true
      tags: [/vuelo]
  /tripulacion/:
    get:
      summary: /tripulacion getAll
      operationId: /tripulacion_getAll
      responses:
        '200': {description: Response 200}
      tags: [/tripulacion]
info: {description: FuourTeam API description, title: FourTeam API, version: 1.0.1}
tags:
- {name: /vuelo, description: /vuelo_descripcion}
- {name: /tripulacion, description: /tripulacion_descripcion}
- {name: /aeronave, description: /aeronave_descripcion}
